configuration:
    # enable_two_stage: True
    enable_two_stage: False
    model: 'resnet18'

    ratio_th: [0.9, 0.9, 0.9, 0.9, 0.95, 1.0]
    # ratio_th: [0.7, 0.8, 0.8, 0.8, 0.9, 1.0]
    # ratio_th: [0.7, 0.7, 0.7, 0.8, 0.8, 0.8]

    # bidirectional: True
    bidirectional: False
    
    display_results: True
    output_directory: 'results'

    layers: [[
                'relu'
            ],
            [
                'maxpool',
                'layer1.0.relu',
                'layer1.0',
                'layer1.1.relu',
                'layer1.1'
            ],
            [
                'layer2.0.relu',
                'layer2.0',
                'layer2.1.relu',
                'layer2.1'
            ],
            [
                'layer3.0.relu',
                'layer3.0',
                'layer3.1.relu',
                'layer3.1'
            ],
            [
                'layer4.0.relu',
                'layer4.0',
                'layer4.1.relu',
                'layer4.1'
            ]]
