configuration:
    
    # enable_two_stage: True
    enable_two_stage: False


    model: 'resnet152'

    # ratio_th: [0.9, 0.9, 0.9, 0.9, 0.95, 1.0]
    # ratio_th: [0.7, 0.8, 0.8, 0.8, 0.9, 1.0]

    ratio_th: [0.99, 0.99, 0.99, 0.99, 0.99, 1.0]

    
    bidirectional: True
    # bidirectional: False

    
    display_results: True
    output_directory: 'results'


    layers: [
                'relu': 'relu',
                'layer1': 'layer1',
                'layer2': 'layer2',
                'layer3': 'layer3',
                'layer4.0': 'layer4.0',
                # 'layer4.1': 'layer4.1',
            ]