configuration:
    enable_two_stage: False
    model: 'vgg19'
    ratio_th: [0.9, 0.9, 0.9, 0.9, 0.95, 1.0]
    bidirectional: True
    display_results: True
    output_directory: 'results'
    layers: [['features.0', 'features.1', 'features.2', 'features.3'],
            ['features.4', 'features.5', 'features.6', 'features.7', 'features.8'],
            ['features.9', 'features.10', 'features.11', 'features.12', 'features.13', 'features.14', 'features.15', 'features.16', 'features.17'],
            ['features.18', 'features.19', 'features.20', 'features.21', 'features.22', 'features.23', 'features.24', 'features.25', 'features.26'],
            ]
